type DiagnosticParams = Record<string, any>;

export const makeGameDiagnosticState = ({
  screen, activeRoomId, isWaitingRoomHost, onlineGameRole, isRoomManager, isOnlinePlayer,
  onlineGameCoordinatorSeatId, canCoordinateOnlineGame, canManageRoom, currentUserId, localSeatId,
  hostSeatId, allReady, teamBalanced, displaySeats, message, actionErrorDialog,
  lastActionDiagnostic, remoteActionDiagnostics, lastManualSyncResolution, turnOrderIds,
  initialTurnOrderIds, completedSeatIds, rankingSeatIds, gameEndMode, lastFinishedSeatId,
  continuationRound, unfinishedRaceSeatIds, canShowContinueRaceButton, roll, rollInProgress,
  rollInProgressRef, hostStateSaveKey, hasPendingGameStateSave, isRollLocked, rollLockUntil,
  rollResultReadyAt, effectiveRollResultReadyAt, rollLockClock, rollResultHolding, turnOrderIntro,
  activeTurnOrderIntro, waitingForOnlineTurnOrder, turnIndex, lastAppliedStateVersionRef,
  lastAppliedSequenceRef, syncPipelineDiagnostic, actionPipelineDiagnostic, turnHealthDiagnostic,
  pendingLocalRemoteActionCount, pendingLocalRemoteActionsRef, pendingLocalRemoteActionMetaRef,
  getPendingLocalRemoteActionType, turnActionTimeoutPenaltyBySeatId, activeSeat,
  getTurnActionTimeoutMs, getItemPromptTimeoutMs, processingActionIdsRef, completedActionIdsRef,
  lastMovedSeatId, lastMovedPieceIds, pieces, isMyTurn, canSubmitTurnAction, canRollNow,
  canMoveSelectedPiece, canRequestMove, turnActionBlockReasons, rollActionBlockReasons,
  moveActionBlockReasons, stalledTurnDetected, stalledTurnReason, stalledTurnAgeMs,
  stalledTurnSyncAgeMs, stalledTurnWatchKey, stalledTurnNeedsBranchChoice, stalledTurnFallbackPiece,
  stalledTurnMovablePieces, getStalledTurnSyncResolution, selectedPieceId, selectedPiece, selectedPieceCanMove,
  activeSeatPiecesOnBoard, fallbackMovablePiece, activeMovablePiece, selectedMoveSteps,
  canSeatControlPiece, visibleLogs, boardItems, ownedItems, trapNodes, shieldedPieceIds,
  pendingTrapPlacement, itemPromptTiming, branchChoice, turnActionTimeoutMs,
}: DiagnosticParams) => ({
  screen,
  activeRoomId,
  isRoomHost: isWaitingRoomHost,
  onlineGameRole,
  isRoomManager,
  isOnlinePlayer,
  onlineGameCoordinatorSeatId,
  canCoordinateOnlineGame,
  canManageRoom,
  currentUserId,
  localSeatId,
  hostSeatId,
  allReady,
  teamBalanced,
  seats: displaySeats.map((seat: any) => ({ id: seat.id, label: seat.label, ready: seat.ready, isAI: seat.isAI, isEmpty: seat.isEmpty, isHost: seat.isHost, team: seat.team })),
  message,
  actionErrorDialog,
  lastActionDiagnostic,
  remoteActionDiagnostics,
  lastManualSyncResolution,
  turnOrderIds,
  initialTurnOrderIds,
  completedSeatIds,
  rankingSeatIds,
  gameEndMode,
  lastFinishedSeatId,
  continuationRound,
  unfinishedRaceSeatIds,
  canShowContinueRaceButton,
  roll,
  rollInProgress,
  rollInProgressRef: rollInProgressRef.current,
  hostStateSaveKey,
  hasPendingGameStateSave,
  isRollLocked,
  rollLockUntil,
  rollResultReadyAt,
  effectiveRollResultReadyAt,
  rollLockClock,
  rollResultHolding,
  turnOrderIntro,
  activeTurnOrderIntro,
  waitingForOnlineTurnOrder,
  turnIndex,
  lastAppliedStateVersion: lastAppliedStateVersionRef.current,
  lastAppliedSequence: lastAppliedSequenceRef.current,
  syncPipeline: syncPipelineDiagnostic,
  actionPipeline: actionPipelineDiagnostic,
  turnHealth: turnHealthDiagnostic,
  pendingLocalRemoteActionCount,
  pendingLocalRemoteActions: Array.from(pendingLocalRemoteActionsRef.current).map((key) => {
    const meta = pendingLocalRemoteActionMetaRef.current.get(key);
    return { key, type: meta?.type ?? getPendingLocalRemoteActionType(key), ageMs: meta ? Math.max(0, Date.now() - meta.createdAt) : 0 };
  }),
  turnActionTimeoutPenaltyBySeatId,
  currentTurnActionTimeoutMs: activeSeat ? getTurnActionTimeoutMs(activeSeat.id) : turnActionTimeoutMs,
  currentItemPromptTimeoutMs: getItemPromptTimeoutMs(localSeatId),
  processingActionCount: processingActionIdsRef.current.size,
  completedActionCount: completedActionIdsRef.current.size,
  lastMovedSeatId,
  lastMovedPieceIds,
  pieces: pieces.map((piece: any) => ({ id: piece.id, ownerId: piece.ownerId, nodeId: piece.nodeId, started: piece.started, finished: piece.finished })),
  activeSeat: activeSeat ? { id: activeSeat.id, label: activeSeat.label, name: activeSeat.name, isAI: activeSeat.isAI } : null,
  isMyTurn,
  canSubmitTurnAction,
  canRollNow,
  canMoveSelectedPiece,
  canRequestMove,
  turnActionBlockReasons,
  rollActionBlockReasons,
  moveActionBlockReasons,
  stalledTurn: {
    detected: stalledTurnDetected,
    reason: stalledTurnReason,
    ageMs: stalledTurnAgeMs,
    syncAgeMs: stalledTurnSyncAgeMs,
    recoveryAfterMs: turnActionTimeoutMs,
    watchKey: stalledTurnWatchKey,
    needsBranchChoice: stalledTurnNeedsBranchChoice,
    fallbackPiece: stalledTurnFallbackPiece ? { id: stalledTurnFallbackPiece.id, ownerId: stalledTurnFallbackPiece.ownerId, label: stalledTurnFallbackPiece.label, nodeId: stalledTurnFallbackPiece.nodeId, started: stalledTurnFallbackPiece.started, finished: stalledTurnFallbackPiece.finished } : null,
    movablePieces: stalledTurnMovablePieces.map((piece: any) => ({ id: piece.id, ownerId: piece.ownerId, label: piece.label, nodeId: piece.nodeId, started: piece.started, finished: piece.finished })),
    syncResolution: getStalledTurnSyncResolution(),
  },
  selectedPieceId,
  selectedPieceCanMove,
  activeSeatPiecesOnBoard,
  fallbackMovablePiece: fallbackMovablePiece ? { id: fallbackMovablePiece.id, ownerId: fallbackMovablePiece.ownerId, label: fallbackMovablePiece.label, started: fallbackMovablePiece.started, finished: fallbackMovablePiece.finished, nodeId: fallbackMovablePiece.nodeId } : null,
  activeMovablePiece: activeMovablePiece ? { id: activeMovablePiece.id, ownerId: activeMovablePiece.ownerId, label: activeMovablePiece.label, started: activeMovablePiece.started, finished: activeMovablePiece.finished, nodeId: activeMovablePiece.nodeId } : null,
  movablePiecesForActiveSeat: activeSeat && roll ? pieces
    .filter((piece: any) => canSeatControlPiece(activeSeat, piece) && !piece.finished && (selectedMoveSteps >= 0 || piece.started))
    .map((piece: any) => ({ id: piece.id, ownerId: piece.ownerId, label: piece.label, nodeId: piece.nodeId, started: piece.started, finished: piece.finished })) : [],
  moveSelectionReason: selectedPieceCanMove ? 'selected-piece' : fallbackMovablePiece ? (activeSeatPiecesOnBoard ? 'fallback-on-board' : 'fallback-off-board-first') : 'none',
  selectedPiece: selectedPiece ? { id: selectedPiece.id, ownerId: selectedPiece.ownerId, started: selectedPiece.started, finished: selectedPiece.finished, nodeId: selectedPiece.nodeId } : null,
  logs: visibleLogs.map((log: any) => ({ id: log.id, text: log.text })),
  boardItems,
  ownedItems,
  trapNodes,
  shieldedPieceIds,
  pendingTrapPlacement,
  itemPromptTiming,
  branchChoice,
});
